# Generated by Django 2.0.5 on 2019-06-10 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0002_auto_20190609_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='CookingApp.Recipe'),
        ),
    ]
